// DADOS EXATOS DOS PROFISSIONAIS DO SISTEMA LIVE
export const orbitalProfessionals = [
  {
    id: 1,
    userId: 101,
    name: "João Vidal",
    email: "joao.vidal@remederi.com",
    title: "Especialista em Automação Residencial",
    category: "Tecnologia",
    bio: "Transformo casas em lares inteligentes com as melhores soluções em automação.",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
    skills: ["Automação", "Smart Home", "IoT", "Instalação", "Configuração"],
    hourlyRate: 85,
    rating: 4.9,
    reviewCount: 127,
    availability: "available",
    phone: "+55 11 98765-4321",
    city: "São Paulo",
    state: "SP",
    pix: "joao.vidal@remederi.com",
    orbitRing: 1,
    orbitPosition: 0,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2025-01-20'),
    autoAcceptEnabled: true,
    autoAcceptRadius: 15
  },
  {
    id: 2,
    userId: 102,
    name: "Maria Silva",
    email: "maria.silva@email.com",
    title: "Fisioterapeuta Especializada",
    category: "Saúde",
    bio: "Especialista em reabilitação e fisioterapia preventiva para melhor qualidade de vida.",
    image: "https://images.unsplash.com/photo-1494790108755-2616b612b1e0?w=150&h=150&fit=crop&crop=face",
    skills: ["Fisioterapia", "Reabilitação", "RPG", "Pilates", "Massoterapia"],
    hourlyRate: 75,
    rating: 4.8,
    reviewCount: 89,
    availability: "available",
    phone: "+55 11 99876-5432",
    city: "São Paulo",
    state: "SP",
    pix: "maria.silva@email.com",
    orbitRing: 1,
    orbitPosition: 1,
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2025-01-22'),
    autoAcceptEnabled: false,
    autoAcceptRadius: 10
  },
  {
    id: 3,
    userId: 103,
    name: "Carlos Pereira",
    email: "carlos.pereira@gmail.com",
    title: "Desenvolvedor Full Stack",
    category: "Tecnologia",
    bio: "Desenvolvedor experiente em React, Node.js e sistemas web modernos.",
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
    skills: ["React", "Node.js", "TypeScript", "PostgreSQL", "AWS"],
    hourlyRate: 120,
    rating: 4.9,
    reviewCount: 156,
    availability: "available",
    phone: "+55 11 97654-3210",
    city: "São Paulo",
    state: "SP",
    pix: "carlos.pereira@gmail.com",
    orbitRing: 1,
    orbitPosition: 2,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2025-01-23'),
    autoAcceptEnabled: true,
    autoAcceptRadius: 20
  },
  {
    id: 4,
    userId: 104,
    name: "Ana Costa",
    email: "ana.costa@hotmail.com",
    title: "Designer UX/UI",
    category: "Design",
    bio: "Crio experiências digitais incríveis com foco na usabilidade e conversão.",
    image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
    skills: ["UX Design", "UI Design", "Figma", "Prototipagem", "User Research"],
    hourlyRate: 95,
    rating: 4.7,
    reviewCount: 73,
    availability: "available",
    phone: "+55 11 96543-2109",
    city: "São Paulo",
    state: "SP",
    pix: "ana.costa@hotmail.com",
    orbitRing: 1,
    orbitPosition: 3,
    createdAt: new Date('2024-03-05'),
    updatedAt: new Date('2025-01-21'),
    autoAcceptEnabled: false,
    autoAcceptRadius: 12
  },
  {
    id: 5,
    userId: 105,
    name: "Roberto Lima",
    email: "roberto.lima@yahoo.com",
    title: "Eletricista Certificado",
    category: "Casa e Construção",
    bio: "Serviços elétricos residenciais e comerciais com segurança e qualidade.",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face",
    skills: ["Instalação Elétrica", "Manutenção", "Quadros Elétricos", "NR-10", "Automação"],
    hourlyRate: 65,
    rating: 4.8,
    reviewCount: 142,
    availability: "available",
    phone: "+55 11 95432-1098",
    city: "São Paulo",
    state: "SP",
    pix: "roberto.lima@yahoo.com",
    orbitRing: 1,
    orbitPosition: 4,
    createdAt: new Date('2024-01-30'),
    updatedAt: new Date('2025-01-24'),
    autoAcceptEnabled: true,
    autoAcceptRadius: 18
  },
  {
    id: 6,
    userId: 106,
    name: "Juliana Santos",
    email: "juliana.santos@gmail.com",
    title: "Psicóloga Clínica",
    category: "Saúde",
    bio: "Atendimento psicológico com abordagem cognitivo-comportamental.",
    image: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150&h=150&fit=crop&crop=face",
    skills: ["Terapia", "TCC", "Ansiedade", "Depressão", "Relacionamentos"],
    hourlyRate: 80,
    rating: 4.9,
    reviewCount: 98,
    availability: "available",
    phone: "+55 11 94321-0987",
    city: "São Paulo",
    state: "SP",
    pix: "juliana.santos@gmail.com",
    orbitRing: 1,
    orbitPosition: 5,
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2025-01-25'),
    autoAcceptEnabled: false,
    autoAcceptRadius: 8
  },
  // ANEL 2 - 7 PROFISSIONAIS
  {
    id: 7,
    userId: 107,
    name: "Pedro Oliveira",
    email: "pedro.oliveira@email.com",
    title: "Personal Trainer",
    category: "Saúde e Fitness",
    bio: "Treinamento personalizado para seus objetivos de saúde e fitness.",
    image: "https://images.unsplash.com/photo-1507081323647-4d250478b919?w=150&h=150&fit=crop&crop=face",
    skills: ["Musculação", "Funcional", "Cardio", "Nutrição", "Reabilitação"],
    hourlyRate: 60,
    rating: 4.6,
    reviewCount: 67,
    availability: "available",
    phone: "+55 11 93210-9876",
    city: "São Paulo",
    state: "SP",
    pix: "pedro.oliveira@email.com",
    orbitRing: 2,
    orbitPosition: 0,
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2025-01-26'),
    autoAcceptEnabled: true,
    autoAcceptRadius: 14
  },
  {
    id: 8,
    userId: 108,
    name: "Fernanda Rocha",
    email: "fernanda.rocha@hotmail.com",
    title: "Advogada Especializada",
    category: "Jurídico",
    bio: "Consultoria jurídica empresarial e direito do consumidor.",
    image: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=150&h=150&fit=crop&crop=face",
    skills: ["Direito Empresarial", "Contratos", "Consumidor", "Trabalhista", "Consultoria"],
    hourlyRate: 150,
    rating: 4.8,
    reviewCount: 45,
    availability: "available",
    phone: "+55 11 92109-8765",
    city: "São Paulo",
    state: "SP",
    pix: "fernanda.rocha@hotmail.com",
    orbitRing: 2,
    orbitPosition: 1,
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2025-01-27'),
    autoAcceptEnabled: false,
    autoAcceptRadius: 25
  },
  {
    id: 9,
    userId: 109,
    name: "Ricardo Almeida",
    email: "ricardo.almeida@gmail.com",
    title: "Chef de Cozinha",
    category: "Gastronomia",
    bio: "Chef especializado em alta gastronomia e eventos personalizados.",
    image: "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=150&h=150&fit=crop&crop=face",
    skills: ["Alta Gastronomia", "Eventos", "Confeitaria", "Vinhos", "Menu Personalizado"],
    hourlyRate: 90,
    rating: 4.9,
    reviewCount: 112,
    availability: "available",
    phone: "+55 11 91098-7654",
    city: "São Paulo",
    state: "SP",
    pix: "ricardo.almeida@gmail.com",
    orbitRing: 2,
    orbitPosition: 2,
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2025-01-28'),
    autoAcceptEnabled: true,
    autoAcceptRadius: 16
  },
  {
    id: 10,
    userId: 110,
    name: "Camila Ferreira",
    email: "camila.ferreira@yahoo.com",
    title: "Arquiteta de Interiores",
    category: "Design",
    bio: "Projetos de arquitetura e design de interiores personalizados.",
    image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&h=150&fit=crop&crop=face",
    skills: ["Arquitetura", "Design Interior", "AutoCAD", "3D", "Sustentabilidade"],
    hourlyRate: 110,
    rating: 4.7,
    reviewCount: 84,
    availability: "available",
    phone: "+55 11 90987-6543",
    city: "São Paulo",
    state: "SP",
    pix: "camila.ferreira@yahoo.com",
    orbitRing: 2,
    orbitPosition: 3,
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2025-01-29'),
    autoAcceptEnabled: false,
    autoAcceptRadius: 22
  },
  {
    id: 11,
    userId: 111,
    name: "Bruno Cardoso",
    email: "bruno.cardoso@email.com",
    title: "Contador Especializado",
    category: "Financeiro",
    bio: "Contabilidade empresarial e planejamento tributário eficiente.",
    image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&h=150&fit=crop&crop=face",
    skills: ["Contabilidade", "Impostos", "Planejamento", "Auditoria", "Consultoria"],
    hourlyRate: 85,
    rating: 4.8,
    reviewCount: 91,
    availability: "available",
    phone: "+55 11 89876-5432",
    city: "São Paulo",
    state: "SP",
    pix: "bruno.cardoso@email.com",
    orbitRing: 2,
    orbitPosition: 4,
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2025-01-30'),
    autoAcceptEnabled: true,
    autoAcceptRadius: 20
  },
  {
    id: 12,
    userId: 112,
    name: "Luciana Martins",
    email: "luciana.martins@gmail.com",
    title: "Veterinária",
    category: "Saúde Animal",
    bio: "Cuidados veterinários completos para seus animais de estimação.",
    image: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=150&h=150&fit=crop&crop=face",
    skills: ["Clínica Geral", "Cirurgia", "Vacinas", "Emergência", "Nutrição Animal"],
    hourlyRate: 70,
    rating: 4.9,
    reviewCount: 138,
    availability: "available",
    phone: "+55 11 88765-4321",
    city: "São Paulo",
    state: "SP",
    pix: "luciana.martins@gmail.com",
    orbitRing: 2,
    orbitPosition: 5,
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2025-01-31'),
    autoAcceptEnabled: false,
    autoAcceptRadius: 12
  },
  {
    id: 13,
    userId: 113,
    name: "Diego Silva",
    email: "diego.silva@hotmail.com",
    title: "Marketing Digital",
    category: "Marketing",
    bio: "Estratégias de marketing digital para crescimento do seu negócio.",
    image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&h=150&fit=crop&crop=face",
    skills: ["SEO", "Google Ads", "Facebook Ads", "Analytics", "E-commerce"],
    hourlyRate: 75,
    rating: 4.6,
    reviewCount: 76,
    availability: "available",
    phone: "+55 11 87654-3210",
    city: "São Paulo",
    state: "SP",
    pix: "diego.silva@hotmail.com",
    orbitRing: 2,
    orbitPosition: 6,
    createdAt: new Date('2024-03-15'),
    updatedAt: new Date('2025-02-01'),
    autoAcceptEnabled: true,
    autoAcceptRadius: 18
  },
  // ANEL 3 - 7 PROFISSIONAIS  
  {
    id: 14,
    userId: 114,
    name: "Patrícia Gomes",
    email: "patricia.gomes@yahoo.com",
    title: "Professora de Idiomas",
    category: "Educação",
    bio: "Aulas particulares de inglês e espanhol para todos os níveis.",
    image: "https://images.unsplash.com/photo-1607746882042-944635dfe10e?w=150&h=150&fit=crop&crop=face",
    skills: ["Inglês", "Espanhol", "Conversação", "Business English", "TOEFL"],
    hourlyRate: 50,
    rating: 4.8,
    reviewCount: 103,
    availability: "available",
    phone: "+55 11 86543-2109",
    city: "São Paulo",
    state: "SP",
    pix: "patricia.gomes@yahoo.com",
    orbitRing: 3,
    orbitPosition: 0,
    createdAt: new Date('2024-02-25'),
    updatedAt: new Date('2025-02-02'),
    autoAcceptEnabled: false,
    autoAcceptRadius: 10
  },
  {
    id: 15,
    userId: 115,
    name: "Marcos Vieira",
    email: "marcos.vieira@gmail.com",
    title: "Mecânico Automotivo",
    category: "Automotivo",
    bio: "Manutenção e reparo de veículos com qualidade e confiança.",
    image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=150&h=150&fit=crop&crop=face",
    skills: ["Mecânica Geral", "Motor", "Freios", "Suspensão", "Injeção Eletrônica"],
    hourlyRate: 55,
    rating: 4.7,
    reviewCount: 129,
    availability: "available",
    phone: "+55 11 85432-1098",
    city: "São Paulo",
    state: "SP",
    pix: "marcos.vieira@gmail.com",
    orbitRing: 3,
    orbitPosition: 1,
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2025-02-03'),
    autoAcceptEnabled: true,
    autoAcceptRadius: 15
  },
  {
    id: 16,
    userId: 116,
    name: "Gabriela Costa",
    email: "gabriela.costa@email.com",
    title: "Esteticista",
    category: "Beleza",
    bio: "Tratamentos estéticos faciais e corporais personalizados.",
    image: "https://images.unsplash.com/photo-1594824804732-ca58d508c447?w=150&h=150&fit=crop&crop=face",
    skills: ["Limpeza de Pele", "Peeling", "Microagulhamento", "Massagem", "Drenagem"],
    hourlyRate: 45,
    rating: 4.9,
    reviewCount: 167,
    availability: "available",
    phone: "+55 11 84321-0987",
    city: "São Paulo",
    state: "SP",
    pix: "gabriela.costa@email.com",
    orbitRing: 3,
    orbitPosition: 2,
    createdAt: new Date('2024-03-20'),
    updatedAt: new Date('2025-02-04'),
    autoAcceptEnabled: false,
    autoAcceptRadius: 8
  }
];

export const initialUsers = [
  {
    id: 1,
    email: "passosmir4@gmail.com",
    password: "m6m7m8M9!horus",
    username: "admin",
    displayName: "Admin Master",
    userType: "admin" as const,
    adminLevel: 10,
    emailVerified: true,
    tokensPlano: 0,
    tokensGanhos: 0,
    tokensComprados: 0,
    tokensUsados: 0,
    creditosAcumulados: 0,
    creditosSacados: 0,
    createdAt: new Date('2024-01-01'),
    protected: true
  },
  {
    id: 2,
    email: "mariahelena@gmail.com", 
    password: "user123",
    username: "mariahelena",
    displayName: "Maria Helena",
    userType: "client" as const,
    adminLevel: 0,
    emailVerified: true,
    tokensPlano: 0,
    tokensGanhos: 0,
    tokensComprados: 4320, // R$ 6,00 convertido
    tokensUsados: 0,
    creditosAcumulados: 0,
    creditosSacados: 0,
    plan: "basic",
    createdAt: new Date('2024-01-10'),
    protected: true
  },
  {
    id: 3,
    email: "phpg69@gmail.com",
    password: "user123", 
    username: "pedro",
    displayName: "Pedro",
    userType: "client" as const,
    adminLevel: 0,
    emailVerified: true,
    tokensPlano: 0,
    tokensGanhos: 0,
    tokensComprados: 2160, // R$ 3,00 convertido  
    tokensUsados: 0,
    creditosAcumulados: 0,
    creditosSacados: 0,
    plan: "free",
    createdAt: new Date('2024-01-15'),
    protected: true
  },
  {
    id: 4,
    email: "joao.vidal@remederi.com",
    password: "pro123",
    username: "joaovidal", 
    displayName: "João Vidal",
    userType: "professional" as const,
    adminLevel: 0,
    emailVerified: true,
    tokensPlano: 23040, // Galaxy Vault R$ 32
    tokensGanhos: 0,
    tokensComprados: 0,
    tokensUsados: 0,
    creditosAcumulados: 0,
    creditosSacados: 0,
    plan: "max",
    createdAt: new Date('2024-01-20'),
    protected: true
  }
];