// This file is automatically generated. Do not edit it directly.
// REDIRECTED TO CENTRALIZED SUPABASE CLIENT
import supabase from '@/lib/supabase';

// Re-export the centralized supabase client
export { supabase };